---
development:
  cloud_name: dux7sk602
  api_key: '537884986744854'
  api_secret: cVIHAW-A7DQzG9gLLpqpbGct-64
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dux7sk602
  api_key: '537884986744854'
  api_secret: cVIHAW-A7DQzG9gLLpqpbGct-64
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dux7sk602
  api_key: '537884986744854'
  api_secret: cVIHAW-A7DQzG9gLLpqpbGct-64
  enhance_image_tag: true
  static_file_support: false
